# -*- coding: UTF-8 -*- 
__author__ = 'zengzheying'


PAGE_SIZE = 20

#新闻类别

NEWS_CATALOG_RECOMMEND = 1  #推荐
NEWS_CATALOG_CIVIL = 2  #国内
NEWS_CATALOG_INTERNATIONAL = 3  #国际
NEWS_CATALOG_SPORT = 4  #体育
NEWS_CATALOG_ENTERTAINMENT = 5  #娱乐
NEWS_CATALOG_ENVIRONMENTAL = 6  #环保
NEWS_CATALOG_SOCIETY = 7  #社会
NEWS_CATALOG_SCIENTIST = 8  #科技
NEWS_CATALOG_FINANCE = 9  #财经


#错误码相关
NOT_AVAILABLE_REQUEST_PARAMETERS = 1001   #无效的请求参数