# -*- coding: UTF-8 -*- 
__author__ = 'zengzheying'


PAGE_SIZE = 20

#新闻类别

NEWS_CATALOG_RECOMMEND = 1  #推荐
NEWS_CATALOG_CIVIL = 2  #国内
NEWS_CATALOG_INTERNATIONAL = 3  #国际
NEWS_CATALOG_SPORT = 4  #体育
NEWS_CATALOG_ENTERTAINMENT = 5  #娱乐
NEWS_CATALOG_ENVIRONMENTAL = 6  #环保
NEWS_CATALOG_SOCIETY = 7  #社会
NEWS_CATALOG_SCIENTIST = 8  #科技
NEWS_CATALOG_FINANCE = 9  #财经

STRING_NEWS_CATALOG_CIVIL = '国内'
STRING_NEWS_CATALOG_INTERNATIONAL = '国际'
STRING_NEWS_CATALOG_SPORT = '体育'
STRING_NEWS_CATALOG_ENTERTAINMENT = '娱乐'
STRING_NEWS_CATALOG_ENVIRONMENTAL = '环保'
STRING_NEWS_CATALOG_SOCIETY = '社会'
STRING_NEWS_CATALOG_SCIENTIST = '科技'
STRING_NEWS_CATALOG_FINANCE = '财经'


#错误码相关
RESULT_OK = 0
STRING_RESULT_OK = '请求已完成'
NOT_AVAILABLE_REQUEST_PARAMETERS = 1001   #无效的请求参数
STRING_NOT_AVAILABLE_REQUEST_PARAMETERS = '无效请求参数'
UID_NOT_MATCH = 1002
STRING_UID_NOT_MATCH = '用户身份不匹配'
